export const fungiData = [
  // --- 1-9: 原有的經典真菌 ---
  {
    id: 1,
    name: "毒蠅傘",
    scientificName: "Amanita muscaria",
    type: "toxic",
    isToxic: true,
    isEdible: false,
    image: "/fungi/1.png",
    description: "童話故事中最經典的紅底白點蘑菇。外表可愛但具有強烈神經毒性。",
    details: "毒蠅傘含有蠅蕈素，攝入後會導致視聽幻覺、肌肉抽搐和昏睡。在西伯利亞薩滿教歷史中，薩滿巫師曾用它來進入『靈界』。",
    tags: ["神經毒性", "致幻", "針葉林"],
    season: "秋季",
    danger: "★★★★☆"
  },
  {
    id: 2,
    name: "美味牛肝菌",
    scientificName: "Boletus edulis",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/2.png",
    description: "世界公認的『菇中之王』，肉質肥厚，帶有堅果與泥土的濃郁香氣。",
    details: "牛肝菌富含蛋白質與礦物質。其特徵是菌蓋下沒有菌褶，而是海綿狀的管口。非常難以人工栽培，市面上的牛肝菌多為野生採集。",
    tags: ["頂級食材", "堅果香", "海綿管口"],
    season: "夏末至秋季",
    danger: "☆☆☆☆☆"
  },
  {
    id: 3,
    name: "夜光蘑菇",
    scientificName: "Mycena chlorophos",
    type: "magic",
    bioluminescent: true,
    isToxic: false, 
    isEdible: false,
    image: "/fungi/3.png",
    description: "在雨季的夜晚會發出令人驚嘆的綠色螢光，宛如森林中的幽靈燈。",
    details: "發光機制涉及螢光素酶氧化螢光素。科學家推測發光可能是為了在夜間吸引夜行性昆蟲（如飛蛾）來幫助傳播孢子。",
    tags: ["生物發光", "夜間限定", "亞熱帶"],
    season: "夏季雨後",
    danger: "★☆☆☆☆"
  },
  {
    id: 4,
    name: "猴頭菇",
    scientificName: "Hericium erinaceus",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/4.png",
    description: "長得像瀑布般的白色長毛，又像猴子的腦袋，是藥食同源的珍品。",
    details: "猴頭菇不僅口感像肉，還含有能夠刺激神經生長的化合物，被認為有潛力預防阿茲海默症。",
    tags: ["藥用價值", "神經修復", "素食肉"],
    season: "秋季",
    danger: "☆☆☆☆☆"
  },
  {
    id: 5,
    name: "鱗柄白鵝膏 (毀滅天使)",
    scientificName: "Amanita virosa",
    type: "toxic",
    isToxic: true,
    isEdible: false,
    image: "/fungi/5.png", 
    description: "潔白無瑕的優雅外表下，藏著致死率極高的鵝膏毒肽。",
    details: "千萬不要被它純白的外表欺騙。只要食用半朵就足以破壞成年人的肝臟與腎臟。中毒症狀通常有潛伏期，等到發現時往往已經造成不可逆的器官衰竭。",
    tags: ["致命", "肝臟破壞", "純白殺手"],
    season: "夏秋季",
    danger: "★★★★★"
  },
  {
    id: 6,
    name: "雞油菌",
    scientificName: "Cantharellus cibarius",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/6.png",
    description: "鮮豔的金黃色，散發著淡淡的杏桃果香，法國料理中的常客。",
    details: "雞油菌是少數蟲子不愛吃的蘑菇，因為它們含有天然的殺蟲成分。口感彈牙，適合奶油慢煎。",
    tags: ["杏桃香", "法式料理", "抗蟲"],
    season: "夏秋季",
    danger: "☆☆☆☆☆"
  },
  {
    id: 7,
    name: "長裙竹蓀",
    scientificName: "Phallus indusiatus",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/7.png",
    description: "被稱為『雪裙仙子』，菌蓋下垂著白色的蕾絲網狀裙，極為優美。",
    details: "竹蓀生長速度極快，那層漂亮的白色網裙會在短短幾小時內展開並凋謝。古代是進貢皇室的珍品。",
    tags: ["真菌皇后", "網狀裙", "生長迅速"],
    season: "夏季",
    danger: "☆☆☆☆☆"
  },
  {
    id: 8,
    name: "冬蟲夏草",
    scientificName: "Ophiocordyceps sinensis",
    type: "magic",
    isToxic: false,
    isEdible: true,
    image: "/fungi/8.png",
    description: "真正的『殭屍真菌』，冬天是蟲，夏天變成草（真菌）。",
    details: "這是一種寄生真菌，孢子感染蝙蝠蛾的幼蟲後，會控制幼蟲爬到接近地表處死亡，接著菌絲吞噬蟲體。",
    tags: ["寄生", "殭屍真菌", "珍貴藥材"],
    season: "夏季採集",
    danger: "★☆☆☆☆"
  },
  {
    id: 9,
    name: "墨汁鬼傘",
    scientificName: "Coprinopsis atramentaria",
    type: "toxic",
    isToxic: true,
    isEdible: false,
    image: "/fungi/9.png",
    description: "成熟後會『自溶』變成黑色墨汁。若搭配酒精食用會導致中毒。",
    details: "含有鬼傘素（Coprine），會阻礙酒精代謝。如果你吃完它三天內喝酒，會出現嚴重的宿醉反應，被稱為『戒酒菇』。",
    tags: ["自溶", "戒酒菇", "不可配酒"],
    season: "春至秋季",
    danger: "★★★☆☆"
  },
  
  // --- 10-20: 頂級食用與致命劇毒 ---
  {
    id: 10,
    name: "黑松露",
    scientificName: "Tuber melanosporum",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/10.png",
    description: "餐桌上的黑色鑽石，生長在地下，需要靠豬或狗來尋找。",
    details: "散發著麝香、潮濕泥土的複雜香氣。它們與橡樹根部共生，無法像普通蘑菇一樣簡單種植。",
    tags: ["地下生長", "昂貴", "共生"],
    season: "冬季",
    danger: "☆☆☆☆☆"
  },
  {
    id: 11,
    name: "羊肚菌",
    scientificName: "Morchella esculenta",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/11.png",
    description: "外觀像蜂巢一樣的珍稀蘑菇，口感脆嫩，西餐中的極品。",
    details: "一定要完全煮熟才能食用，生食含有微量毒素。其獨特的蜂窩狀結構能吸附醬汁，風味極佳。",
    tags: ["蜂巢狀", "需煮熟", "高級食材"],
    season: "春季",
    danger: "★☆☆☆☆"
  },
  {
    id: 12,
    name: "死帽蕈 (綠褶菇)",
    scientificName: "Amanita phalloides",
    type: "toxic",
    isToxic: true,
    isEdible: false,
    image: "/fungi/12.png",
    description: "菇界頭號殺手，世界上大部分的蘑菇致死案例都由它造成。",
    details: "只要30克（約半朵）就足以讓成人死亡。其毒素耐熱，烹飪無法分解。初期症狀緩解後會進入『假癒期』，隨後肝腎功能全面崩潰。",
    tags: ["極度致命", "無解藥", "世界最毒"],
    season: "夏秋季",
    danger: "★★★★★"
  },
  {
    id: 13,
    name: "松茸",
    scientificName: "Tricholoma matsutake",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/13.png",
    description: "日本飲食文化的靈魂，具有獨特的濃烈松脂香氣。",
    details: "對生長環境極度挑剔，只能生長在赤松林的根部，至今仍難以大規模人工栽培，因此價格居高不下。",
    tags: ["松脂香", "日本珍味", "無法栽培"],
    season: "秋季",
    danger: "☆☆☆☆☆"
  },
  {
    id: 14,
    name: "鹿花菌",
    scientificName: "Gyromitra esculenta",
    type: "toxic",
    isToxic: true,
    isEdible: false,
    image: "/fungi/14.png",
    description: "外型像大腦，含有火箭燃料成分的劇毒蘑菇。",
    details: "含有甲基聯氨（火箭燃料成分）。但在芬蘭等地，經過特殊的多次水煮處理後被視為美食，但處理不當即會致死。",
    tags: ["像大腦", "火箭燃料", "條件可食"],
    season: "春季",
    danger: "★★★★☆"
  },
  {
    id: 15,
    name: "靈芝",
    scientificName: "Ganoderma lucidum",
    type: "magic",
    isToxic: false,
    isEdible: true,
    image: "/fungi/15.png",
    description: "東方傳說中的『仙草』，質地堅硬如木頭，多用於藥用。",
    details: "富含多醣體與三萜類化合物，被廣泛用於提升免疫力。它不是用來吃的（太硬），而是切片煮茶或萃取。",
    tags: ["藥用", "木質化", "免疫調節"],
    season: "全年",
    danger: "☆☆☆☆☆"
  },
  {
    id: 16,
    name: "巨型馬勃",
    scientificName: "Calvatia gigantea",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/16.png",
    description: "像一顆巨大的白色足球，內部全白時可食用。",
    details: "可以長到比籃球還大。切開如果內部是純白如豆腐，就可以像排餐一樣煎來吃；若變黃則代表孢子已成熟，不可食用。",
    tags: ["巨大", "像足球", "幼嫩可食"],
    season: "夏末秋初",
    danger: "☆☆☆☆☆"
  },
  {
    id: 17,
    name: "藍瘦香菇 (霍氏粉褶菌)",
    scientificName: "Entoloma hochstetteri",
    type: "toxic",
    isToxic: true,
    isEdible: false,
    image: "/fungi/17.png",
    description: "全株呈現夢幻的亮藍色，紐西蘭鈔票上的圖案。",
    details: "這種不可思議的藍色來自於一種甘菊藍類色素。雖然非常美麗，但被認為不可食用（毒性不明確，建議觀賞）。",
    tags: ["亮藍色", "夢幻", "紐西蘭"],
    season: "秋季",
    danger: "★★★☆☆"
  },
  {
    id: 18,
    name: "出血齒菌",
    scientificName: "Hydnellum peckii",
    type: "toxic",
    isToxic: false,
    isEdible: false,
    image: "/fungi/18.png",
    description: "外號『草莓與奶油』，表面會滲出鮮紅色的液體。",
    details: "雖然無毒，但味道極其苦澀難以入口。那些紅色的液體其實是真菌排出多餘水分與色素的現象（Guttation）。",
    tags: ["像流血", "極苦", "奇觀"],
    season: "秋季",
    danger: "★☆☆☆☆"
  },
  {
    id: 19,
    name: "雲芝",
    scientificName: "Trametes versicolor",
    type: "magic",
    isToxic: false,
    isEdible: false,
    image: "/fungi/19.png",
    description: "像火雞尾巴一樣層層疊疊的扇形真菌，常見的森林分解者。",
    details: "具有強大的藥用價值，其中的 PSK 成分被用於輔助癌症治療。質地如皮革，通常用來煮茶。",
    tags: ["層疊狀", "抗癌研究", "木棲"],
    season: "全年",
    danger: "☆☆☆☆☆"
  },
  {
    id: 20,
    name: "冬菇 (金針菇)",
    scientificName: "Flammulina velutipes",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/20.png",
    description: "野生的金針菇其實是橘黃色的，且菌蓋較大。",
    details: "我們超市買到的白色細長金針菇是人工在無光環境下培育的結果。野生種耐寒性極強，甚至能在雪地裡生長。",
    tags: ["耐寒", "超市常見", "野生不同"],
    season: "冬季",
    danger: "☆☆☆☆☆"
  },

  // --- 21-30: 怪奇與視覺系 ---
  {
    id: 21,
    name: "阿切氏籠頭菌 (惡魔手指)",
    scientificName: "Clathrus archeri",
    type: "toxic",
    isToxic: true,
    isEdible: false,
    image: "/fungi/21.png",
    description: "從蛋狀物中孵化出紅色的觸手，散發著腐肉的臭味。",
    details: "看起來像外星生物。它利用腐臭味吸引蒼蠅來幫助傳播孢子。雖然無劇毒，但那個味道絕對讓你不想吃它。",
    tags: ["像觸手", "腐臭", "外星生物"],
    season: "夏秋季",
    danger: "★★☆☆☆"
  },
  {
    id: 22,
    name: "多形炭角菌 (死人手指)",
    scientificName: "Xylaria polymorpha",
    type: "toxic",
    isToxic: true,
    isEdible: false,
    image: "/fungi/22.png",
    description: "從枯木中伸出黑色的、殭屍般的手指，令人毛骨悚然。",
    details: "質地堅硬如木炭。它們是木材腐朽菌，雖然看起來很可怕，但在森林生態循環中扮演重要角色。",
    tags: ["恐怖", "像手指", "木炭質地"],
    season: "全年",
    danger: "★☆☆☆☆"
  },
  {
    id: 23,
    name: "靛藍乳菇",
    scientificName: "Lactarius indigo",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/23.png",
    description: "切開後會流出深藍色的乳汁，顏色鮮豔得像油漆。",
    details: "雖然顏色看起來像有毒，但它其實是可食用的，且味道還不錯。烹飪後藍色會稍微變淡。",
    tags: ["藍色乳汁", "可食用", "視覺衝擊"],
    season: "夏秋季",
    danger: "☆☆☆☆☆"
  },
  {
    id: 24,
    name: "鳥巢菌",
    scientificName: "Nidulariaceae",
    type: "magic",
    isToxic: false,
    isEdible: false,
    image: "/fungi/24.png",
    description: "像一個個微小的鳥巢，裡面躺著幾顆『鳥蛋』。",
    details: "那些『鳥蛋』其實是充滿孢子的小包（peridioles）。雨滴打進巢裡時，會利用噴濺力量將孢子包彈射出去。",
    tags: ["微觀奇景", "雨滴傳播", "可愛"],
    season: "秋季",
    danger: "☆☆☆☆☆"
  },
  {
    id: 25,
    name: "紫水晶菇",
    scientificName: "Laccaria amethystina",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/25.png",
    description: "全株呈現通透的紫水晶色，隨著乾燥會變成灰白色。",
    details: "這是一種騙子蘑菇，因為它很容易吸收土壤中的砷（砒霜），如果生長環境受污染就會變得很毒。需在乾淨環境採集。",
    tags: ["紫色", "環境指標", "易混淆"],
    season: "夏秋季",
    danger: "★★☆☆☆"
  },
  {
    id: 26,
    name: "白松露",
    scientificName: "Tuber magnatum",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/26.png",
    description: "世界上最昂貴的食材之一，產自義大利阿爾巴地區。",
    details: "不像黑松露可以加熱，白松露通常是生刨在料理上，因為其香氣遇熱易散。價格是以克計算的。",
    tags: ["極致昂貴", "生食", "義大利"],
    season: "深秋",
    danger: "☆☆☆☆☆"
  },
  {
    id: 27,
    name: "白樺茸",
    scientificName: "Inonotus obliquus",
    type: "magic",
    isToxic: false,
    isEdible: true,
    image: "/fungi/27.png",
    description: "看起來像樺樹上的燒焦木炭，是極強的抗氧化劑。",
    details: "生長在寒冷地區的白樺樹上。其抗氧化能力是靈芝的數倍，常被磨粉沖泡，有『森林鑽石』之稱。",
    tags: ["抗氧化", "像木炭", "超級食物"],
    season: "全年",
    danger: "☆☆☆☆☆"
  },
  {
    id: 28,
    name: "傑克南瓜燈毒菇",
    scientificName: "Omphalotus olearius",
    type: "toxic",
    isToxic: true,
    isEdible: false,
    image: "/fungi/28.png",
    description: "鮮豔的橘色，常被誤認為雞油菌，在黑暗中菌褶會發光。",
    details: "含有毒素，會引起嚴重的胃腸道痙攣。其生物發光現象微弱，需要適應黑暗的眼睛才能看見。",
    tags: ["發光", "易混淆", "橘色"],
    season: "秋季",
    danger: "★★★☆☆"
  },
  {
    id: 29,
    name: "銀耳 (白木耳)",
    scientificName: "Tremella fuciformis",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/29.png",
    description: "晶瑩剔透的膠質真菌，被譽為『平民燕窩』。",
    details: "富含植物性膠原蛋白（多醣體），具有極佳的保濕與潤肺效果。乾燥後呈黃色，泡水後變白。",
    tags: ["美容", "膠質", "潤肺"],
    season: "夏季",
    danger: "☆☆☆☆☆"
  },
  {
    id: 30,
    name: "毛頭鬼傘 (雞腿菇)",
    scientificName: "Coprinus comatus",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/30.png",
    description: "幼嫩時像雞腿一樣美味，但成熟極快會自溶成墨汁。",
    details: "必須在採摘後幾小時內食用，否則就會變成一灘黑水。口感滑嫩鮮美，是城市草地上常見的美味。",
    tags: ["極鮮", "保存困難", "城市常見"],
    season: "雨後",
    danger: "☆☆☆☆☆"
  },

  // --- 31-40: 更多常見與奇特真菌 ---
  {
    id: 31,
    name: "舞菇 (灰樹花)",
    scientificName: "Grifola frondosa",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/31.png",
    description: "傳說發現它的人會高興得手舞足蹈，因此得名。",
    details: "一株可以長得非常巨大（重達數十斤）。具有獨特的香氣與脆嫩口感，且富含增強免疫力的成分。",
    tags: ["巨大", "免疫力", "日式料理"],
    season: "秋季",
    danger: "☆☆☆☆☆"
  },
  {
    id: 32,
    name: "香菇 (冬菇)",
    scientificName: "Lentinula edodes",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/32.png",
    description: "亞洲料理的基石，乾燥後香氣更濃郁（鳥苷酸）。",
    details: "透過乾燥過程會破壞細胞壁，釋放出強烈的鮮味物質（Umami）。是世界上栽培量第二大的食用菌。",
    tags: ["鮮味", "亞洲料理", "栽培廣泛"],
    season: "全年",
    danger: "☆☆☆☆☆"
  },
  {
    id: 33,
    name: "紅菇 (嘔吐紅菇)",
    scientificName: "Russula emetica",
    type: "toxic",
    isToxic: true,
    isEdible: false,
    image: "/fungi/33.png",
    description: "鮮豔的紅色菌蓋，正如其名，吃了會讓你劇烈嘔吐。",
    details: "雖然通常不致死，但會引發劇烈的胃腸炎。在紅菇科中，這是一個『紅色警戒』的代表。",
    tags: ["劇烈嘔吐", "紅色警戒", "辛辣味"],
    season: "夏秋季",
    danger: "★★★☆☆"
  },
  {
    id: 34,
    name: "杏鮑菇",
    scientificName: "Pleurotus eryngii",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/34.png",
    description: "具有杏仁的香氣和鮑魚的口感，菌柄肥厚。",
    details: "原產於地中海地區，現在已是全球常見食材。它的菌柄比菌蓋更好吃，質地緻密。",
    tags: ["素鮑魚", "菌柄好吃", "百搭"],
    season: "全年",
    danger: "☆☆☆☆☆"
  },
  {
    id: 35,
    name: "木耳",
    scientificName: "Auricularia auricula-judae",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/35.png",
    description: "長得像耳朵的膠質真菌，血管清道夫。",
    details: "富含膳食纖維與抗凝血物質。有趣的是，新鮮木耳含有卟啉，光照下可能引起皮膚過敏，建議食用乾貨泡發的。",
    tags: ["血管健康", "膠質", "需泡發"],
    season: "全年",
    danger: "★☆☆☆☆"
  },
  {
    id: 36,
    name: "橙蓋鵝膏 (凱撒磨菇)",
    scientificName: "Amanita caesarea",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/36.png",
    description: "古羅馬皇帝凱撒最愛的蘑菇，鵝膏菌中少見的美味食用種。",
    details: "這是一個例外，雖然屬於劇毒的鵝膏科，但它是頂級美味。不過因為與毒蠅傘的變種長得像，新手不建議採集。",
    tags: ["皇室美食", "易混淆", "頂級"],
    season: "夏季",
    danger: "★★☆☆☆"
  },
  {
    id: 37,
    name: "緋紅肉杯菌",
    scientificName: "Sarcoscypha coccinea",
    type: "magic",
    isToxic: false,
    isEdible: false,
    image: "/fungi/37.png",
    description: "像森林中遺落的小紅酒杯，鮮豔奪目。",
    details: "通常生長在埋在土裡的樹枝上。雖然無毒，但質地硬且沒味道，通常僅作為生態攝影的漂亮模特兒。",
    tags: ["鮮紅", "杯狀", "觀賞性"],
    season: "冬末春初",
    danger: "☆☆☆☆☆"
  },
  {
    id: 38,
    name: "地星",
    scientificName: "Geastrum triplex",
    type: "magic",
    isToxic: false,
    isEdible: false,
    image: "/fungi/38.png",
    description: "外層表皮裂開呈星形，中間包裹著孢子球。",
    details: "當雨滴落在中間的球體上時，會像噴泉一樣噴出孢子煙霧。這是一種非常聰明的物理傳播機制。",
    tags: ["星形", "噴射孢子", "奇特"],
    season: "秋季",
    danger: "☆☆☆☆☆"
  },
  {
    id: 39,
    name: "蛹蟲草 (黃金蟲草)",
    scientificName: "Cordyceps militaris",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/39.png",
    description: "冬蟲夏草的親戚，現在已能人工用米飯培養。",
    details: "含有豐富的蟲草素，價格比野生冬蟲夏草親民許多，常被用於煲湯或保健食品中。",
    tags: ["平民補品", "橘黃色", "人工栽培"],
    season: "全年",
    danger: "☆☆☆☆☆"
  },
  {
    id: 40,
    name: "松露玉蕈 (鴻喜菇)",
    scientificName: "Hypsizygus tessellatus",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/40.png",
    description: "菌蓋有大理石紋路，口感爽脆，適合任何料理。",
    details: "一定要煮熟才能吃，因為生食有苦味且難消化。市面上常見好菇道系列就是這一類。",
    tags: ["爽脆", "常見食材", "需煮熟"],
    season: "全年",
    danger: "☆☆☆☆☆"
  },

  // --- 41-50: 稀有與特殊生態 ---
  {
    id: 41,
    name: "紅汁小菇",
    scientificName: "Mycena haematopus",
    type: "magic",
    isToxic: false,
    isEdible: false,
    image: "/fungi/41.png",
    description: "受傷時會流出紅色的乳汁，像是森林在流血。",
    details: "屬於分解者，生長在腐木上。雖然看起來有點嚇人，但它是森林養分循環的重要功臣。",
    tags: ["流血", "微小", "分解者"],
    season: "秋季",
    danger: "☆☆☆☆☆"
  },
  {
    id: 42,
    name: "條紋黑蛋巢菌",
    scientificName: "Cyathus striatus",
    type: "magic",
    isToxic: false,
    isEdible: false,
    image: "/fungi/42.png",
    description: "杯壁有精緻的條紋，像是迷你編織籃。",
    details: "這是一種更精緻的鳥巢菌，通常生長在木屑堆肥中。是園藝愛好者常在花盆裡發現的小驚喜。",
    tags: ["條紋", "園藝常見", "微觀"],
    season: "夏秋季",
    danger: "☆☆☆☆☆"
  },
  {
    id: 43,
    name: "草菇",
    scientificName: "Volvariella volvacea",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/43.png",
    description: "生長在稻草堆上，口感滑嫩，常包裹在菌托中。",
    details: "是典型的熱帶高溫菇類。一定要趁它還在蛋形（未開傘）時採收，那時候最美味。",
    tags: ["熱帶", "滑嫩", "稻草"],
    season: "夏季",
    danger: "☆☆☆☆☆"
  },
  {
    id: 44,
    name: "狗臭角菌",
    scientificName: "Mutinus caninus",
    type: "toxic",
    isToxic: false,
    isEdible: false,
    image: "/fungi/44.png",
    description: "外型像紅色的狗生殖器，頂端帶有臭味黏液。",
    details: "鬼筆科的一員。那個臭味是為了吸引蒼蠅。雖然幼嫩的蛋形期理論上無毒，但沒人想吃它。",
    tags: ["形狀尷尬", "臭味", "鬼筆科"],
    season: "夏秋季",
    danger: "★☆☆☆☆"
  },
  {
    id: 45,
    name: "苦味夜光菇",
    scientificName: "Panellus stipticus",
    type: "magic",
    bioluminescent: true,
    isToxic: true,
    isEdible: false,
    image: "/fungi/45.png",
    description: "生長在枯木上的小扇貝，在北美東部的菌株會發光。",
    details: "這是一個有趣的生物地理現象：北美東部的會發光，但生長在歐洲的同種卻不會。味道極苦且有毒。",
    tags: ["發光", "極苦", "止血劑"],
    season: "秋季",
    danger: "★★☆☆☆"
  },
  {
    id: 46,
    name: "大蓋小皮傘",
    scientificName: "Marasmius oreades",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/46.png",
    description: "著名的『仙女環』蘑菇，常在草地上排成一圈。",
    details: "含有海藻糖，讓它們具有極強的耐旱性，乾枯後遇水能復活（起死回生）。甜味獨特，適合烤餅乾。",
    tags: ["仙女環", "耐旱", "起死回生"],
    season: "夏秋季",
    danger: "☆☆☆☆☆"
  },
  {
    id: 47,
    name: "滑菇 (納摩菇)",
    scientificName: "Pholiota nameko",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/47.png",
    description: "表面覆蓋著厚厚一層黏液，是日本味噌湯的經典配料。",
    details: "那層黏液其實是多醣體，對胃壁有保護作用。煮熟後黏滑的口感深受喜愛。",
    tags: ["黏液", "味噌湯", "顧胃"],
    season: "深秋",
    danger: "☆☆☆☆☆"
  },
  {
    id: 48,
    name: "致命白毒傘",
    scientificName: "Amanita verna",
    type: "toxic",
    isToxic: true,
    isEdible: false,
    image: "/fungi/48.png",
    description: "被稱為『愚人菇』，因為常被誤認為食用菇而釀成悲劇。",
    details: "春季發生率最高。含有與死帽蕈相同的鵝膏毒肽，死亡率極高。特徵是莖部基部有白色的菌托（袋子）。",
    tags: ["春季殺手", "菌托", "極度致命"],
    season: "春季",
    danger: "★★★★★"
  },
  {
    id: 49,
    name: "裂褶菌",
    scientificName: "Schizophyllum commune",
    type: "toxic",
    isToxic: false,
    isEdible: false,
    image: "/fungi/49.png",
    description: "世界上分佈最廣的真菌，擁有超過 23,000 種性別。",
    details: "雖然在某些文化中被食用，但有報導指出吸入其孢子可能在免疫力低下者的肺部生長，引起感染，因此建議不要隨意把玩。",
    tags: ["多性別", "肺部感染", "極常見"],
    season: "全年",
    danger: "★★☆☆☆"
  },
  {
    id: 50,
    name: "松露 (夏松露)",
    scientificName: "Tuber aestivum",
    type: "edible",
    isToxic: false,
    isEdible: true,
    image: "/fungi/50.png",
    description: "價格較親民的松露品種，香氣比冬松露淡雅。",
    details: "內部切面呈淺褐色。因為產量較大且分佈廣，是入門松露世界的最佳選擇。",
    tags: ["入門款", "淡雅", "夏季"],
    season: "夏季",
    danger: "☆☆☆☆☆"
  }
];